KEYWORDS_BROAD_CANDIDATES = [
    "Transformer",
    "Diffusion Model",
    "Neural Networks",
    "Autoencoder",
    "GPT-3",
    "GPT-4",
    "DALL-E",
    "Stable Diffusion",
    "Midjourney",
    "LLaMA",
    "Bard",
    "StyleGAN",
    "PaLM",
    "GitHub Copilot",
    "OpenAI Codex",
    "Google Gemini",
    "BLOOM",
    "Mistral",
    "T5",
    "Falcon",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Hugging Face",
    "OpenAI API",
    "Google Vertex AI",
    "Amazon SageMaker",
    "Azure OpenAI Service",
    "LangChain",
    "LlamaIndex",
    "Cohere",
    "Pinecone",
    "FAISS",
    "MLOps",
    "LLMOps",
    "Vector Database",
    "Weaviate",
    "OpenAI",
    "Prompt Engineering",
    "Prompt Engineer",
    "Fine-Tuning",
    "Transfer Learning",
    "Zero-Shot Learning",
    "Few-Shot Learning",
    "Reinforcement Learning",
    "Reinforcement Learning from Human Feedback",
    "Self-Supervised Learning",
    "Unsupervised Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Natural Language Generation",
    "Embeddings",
    "LoRA",
    "DreamBooth",
    "Chain-of-Thought",
    "Human-in-the-Loop",
    "AI Alignment",
    "Artificial Intelligence",
    "Machine Learning",
    "Generative AI",
    "Conversational AI",
    "Chatbot",
    "Virtual Assistant",
    "AI-Driven Automation",
    "Intelligent Automation",
    "Digital Transformation",
    "AI Strategy",
    "AI Adoption",
    "AI Ethics",
    "Explainable AI",
    "Responsible AI",
    "Content Generation",
    "Synthetic Media",
    "Deepfake",
    "Creative AI",
    "AI-Powered",
    "Generative Design",
    "Music Generation",
    "AutoGPT",
    "AI Agent",
    "Retrieval-Augmented Generation",
    "Text-to-Speech",
    "Text-to-Image",
    "Text-to-Video",
    "Image Generation",
    "Voice Cloning",
    "Generative Model",
    "Multimodal AI",
    "Artificial General Intelligence",
    "Augmented Intelligence",
    "Hyperautomation",
    "Foundation Model",
    "ChatGPT Plugins",
    "Jasper",
    "Synthesia",
]